### PR TITLE
Create KnownDefects.md

### PR DESCRIPTION
**Pull request by tigju**
Guys, I started to do the documentation from check list, pinch in as well. Thanks.

### CODE REVIEW

**Review by jckaizen — DISMISSED** [review]
Good start on the documentation! Since the stakeholder was moved up to next Monday, we could probably fix some of the issues here

**Review by jckaizen — DISMISSED** [review]
Good job on the documentation!

**Review by cdlafortune — APPROVED** [review]
thanks for creating this documentation!

**Review by jckaizen — APPROVED** [review]
Good job on the documentation!

**Review by DrewRust — APPROVED** [review]
Awesome job Iulia!

**Pull request merged**
